pip3 install sklearn
pip2 install sklearn
pip2 install textblob
pip3 install textblob
pip2 install gluoncv
pip3 install gluoncv
pip2 install mxnet
pip3 install mxnet
pip2 install psutil
pip3 install psutil
